[build]
command = "npm run build"
publish = "/build"
base = "/apps/frontend"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "http://todo-demo-app.ap-northeast-2.elasticbeanstalk.com/:splat"
status = 200
